### ISSUE TITLE
Jetty Releases 12.0.0

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10114]
**Jetty Versions:**
This release process will produce releases: 12.0.0

**Target Date:**
July 28, 2023

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty version(s) in the issue.  
- [x] Update the target release date in the issue.
- [x] Link this issue to the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects).
- [x] Assign this issue to a "release manager".
- [x] Review [draft security advisories](https://github.com/eclipse/jetty.project/security/advisories). Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Update [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects)
  + [x] Create new project for the next releases (not this release).
  + [x] Ensure new project is public (not private)
  + [x] Freeze the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects) by editing their names to "Jetty X.Y.Z FROZEN"
  + [x] Review the issues/PRs assigned to the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects).  Any tasks that are not-yet-started are moved to next releases.
- [x] Review dependabot status. [Manually](https://github.com/eclipse/jetty.project/network/updates) run dependabot if needed and review resulting PRs for inclusion.
- [x] Wait 24 hours from last change to the issues/PRs included in FROZEN GitHub Project(s).
- [x] Verify target [project(s)](https://github.com/eclipse/jetty.project/projects) are complete.
- [x] Verify that branch `jetty-11.0.x` is merged to branch `jetty-12.0.x`.
- [x] Assign issue to "build manager", who will stage the releases.
  + [x] Create and use branches `release/<ver>` to perform version specific release work from.
  + [x] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
  + [x] Stage 12 release with Java 20
  + [x] Push release branches `release/<ver>` to to https://github.com/eclipse/jetty.project
  + [x] Push release tags `jetty-<ver>` to https://github.com/eclipse/jetty.project
  + [x] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
        Be mindful of the order you create multiple release drafts.  The first one created will be the "oldest" when published. (eg: Draft is 9, then 10, then 11)
        The last created "draft" will show up as "latest" in the github UI.
        If you have to reroll, you'll have to delete the drafts and recreate them (especially so if 9 w/timestamp is in the mix of releases being worked on)
- [x] Assign issue to "test manager", who will oversee the testing of the staged releases.
  + [x] Test [CometD](https://github.com/cometd/cometd).
  + [x] Test [Reactive HttpClient](https://github.com/jetty-project/jetty-reactive-httpclient).
  + [x] Test [Load Generator](https://github.com/jetty-project/jetty-load-generator).
  + [x] Test [Jetty Docker images](https://github.com/eclipse/jetty.docker).
  + [x] Test other [Jetty OSS integrations](https://jenkins.webtide.net/job/external_oss).
  + [x] Check [TCK CI](https://jenkins.webtide.net/job/tck).
  + [x] Test sponsored integrations.
  + [x] Check CI for performance regressions.
  + [x] Notify interested parties and invite testing of the staged release(s).
  + [x] Assign issue back to "release manager".
- [x] Collect release votes from committers.
- [x] Promote staged releases.
- [x] Merge release branches back to main branches and delete release branches.
- [x] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [x] Update Jetty versions on the web sites.
  + [x] Update (or check) [Download](https://eclipse.dev/jetty/download.php) page is updated.
  + [x] Update (or check) documentation page(s) are updated.
- [x] Publish GitHub Releases in the order of oldest (eg: 9) to newest (eg: 11) (to ensure that "latest" in github is truly the latest)
- [x] Prepare release announcement for mailing lists.
- [x] Publish any [security advisories](https://github.com/eclipse/jetty.project/security/advisories).
  + [x] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
  + [x] Edit any issues for CVEs in github with their CVE number
- [x] Notify downstream maintainers.
  + [x] Eclipse p2 maintainer.
  + [x] Docker maintainer.
  + [x] Jenkins maintainer.
  + [x] Other maintainers.

**Comment by benstpierre** [comment]
Curious is the target date of July 20 pushed back now?  Just trying to plan our own switch to Jetty 12 (roughly).

**Comment by joakime** [comment]
@benstpierre July 20 obviously didn't happen.
We are tracking a number of issues from various testing of the 12.0.0 staged release.
A bunch of fixes have been made, and even more are being merged right now.
We'll be deploying a 12.0.0.beta4 in the next 24 hours with these fixes as we continue to test the next reroll of 12.0.0 HEAD for release (hopefully mid next week).

**Comment by joakime** [comment]
The last stage of 12.0.0 (from July 20 has been dropped), along with associated branches and tags.
Stay tuned for 12.0.0.beta4 interim release.

**Comment by zUniQueX** [comment]
beta4 is available in Maven Central.

**Comment by joakime** [comment]
New stage of 12.0.0 is now available for testing at https://oss.sonatype.org/content/repositories/jetty-1790/

**Comment by oliveryasuna** [comment]
@joakime How can we find out new staging versions? https://oss.sonatype.org/content/repositories/ doesn't work.

**Comment by joakime** [comment]
@oliveryasuna a staging repo only has 1 version in it.
New staging repos exist in an ephemeral state, only for the time period to test a potential release.
Once testing is complete, the staging repo is either dropped (basically rejected as a release), or promoted (the release migrates to maven central).

You cannot even rely on sequential numbering (like expecting `../jetty-1791/` to be a release of Jetty server, it can easily be one of the other artifacts supported by the Jetty project that isn't the Jetty server itself, even toolchain artifacts)

**Comment by oliveryasuna** [comment]
@joakime I meant how do I find out the next number?

**Comment by joakime** [comment]
@oliveryasuna it is announced, typically in these kinds of release process issues.

**Comment by oliveryasuna** [comment]
@joakime Got it, thank you! But were did 1790 come from? I don't see it mentioned here until you responded to my colleague @benstpierre.

We want to get on 12.0.0. Best way we think is to keep up to date with the latest Jetty 12.0.0 staging in our testing branch.

**Comment by joakime** [comment]
Dropping stage https://oss.sonatype.org/content/repositories/jetty-1790/  (re-rolling with new fixes)

**Comment by joakime** [comment]
Rerolled (on Aug 2) stage of 12.0.0 is now available for testing at https://oss.sonatype.org/content/repositories/jetty-1791/

Reminder: to test demos, you can use the with-staging group repository.

``` shell
java -Dmaven.repo.uri=https://oss.sonatype.org/content/groups/jetty-with-staging/ -jar ../../jetty-home-12.0.0/start.jar --add-module=http,ee10-demos
```

**Comment by joakime** [comment]
A reroll of 12.0.0 is coming due to some last minute bugs

* #10228
* #10232
* #10233

**Comment by joakime** [comment]
Dropping stage https://oss.sonatype.org/content/repositories/jetty-1791/ (re-rolling with new fixes)

**Comment by gregw** [comment]
One more time all together now...

**Comment by joakime** [comment]
New stage of 12.0.0 (Aug 6) available at https://oss.sonatype.org/content/repositories/jetty-1792/

**Comment by joakime** [comment]
Dropping stage https://oss.sonatype.org/content/repositories/jetty-1792/ (Rerolling due to documentation issues fixed this morning)

**Comment by joakime** [comment]
New stage of 12.0.0 (Aug 7) available at https://oss.sonatype.org/content/repositories/jetty-1793/

**Comment by joakime** [comment]
This final stage has been promoted and is now making its way to the various download locations and maven repositories

**Comment by joakime** [comment]
12.0.0 is now verified as being present on maven central - https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/12.0.0/

@jmcc0nn3ll  Time to update the https://eclipse.dev/jetty/ website

**Comment by joakime** [comment]
The Eclipse website is up to date.

Github release is published - https://github.com/eclipse/jetty.project/releases/tag/jetty-12.0.0

Preparing the maililng list announcements now.

The merge of the release branch back to HEAD `jetty-12.0.x` (and bump the version to `12.0.1-SNAPSHOT`) is opened at ...

* #10237

**Comment by joakime** [comment]
Branch `jetty-12.0.x` is now the default branch on this repo.

**Comment by joakime** [comment]
@jmcc0nn3ll the zip hashes on the download page has a typo.

"mp5" vs "md5"

https://eclipse.dev/jetty/download_info.php

Can you get that corrected?

**Comment by jmcc0nn3ll** [comment]
@joakime the text has been updated and will reflect on the website once the eclipse update process runs (soon)

**Comment by joakime** [comment]
All tasks done.
Closing the 12.0.0 project now.
