### ISSUE TITLE
Jetty Release 11.0.17

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#10647]
**Jetty Versions:**
This release process will produce releases:
11.0.17

**Target Date:**
7 October 2023

**Tasks:**
- [x] Create the release(s) issue.
- [X] Update the target Jetty version(s) in the issue.  
- [X] Update the target release date in the issue.
- [x] Link this issue to the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects).
- [x] Assign this issue to a "release manager".
- [x] Review [draft security advisories](https://github.com/eclipse/jetty.project/security/advisories). Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Update [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects)
  + [x] Create new project for the next releases (not this release).
  + [x] Ensure new project is public (not private)
  + [x] Freeze the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects) by editing their names to "Jetty X.Y.Z FROZEN"
  + [x] Review the issues/PRs assigned to the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects).  Any tasks that are not-yet-started are moved to next releases.
- [x] Review dependabot status. [Manually](https://github.com/eclipse/jetty.project/network/updates) run dependabot if needed and review resulting PRs for inclusion.
- [x] Wait 24 hours from last change to the issues/PRs included in FROZEN GitHub Project(s).
- [x] Verify target [project(s)](https://github.com/eclipse/jetty.project/projects) are complete.
- [x] Verify that branch `jetty-10.0.x` is merged to branch `jetty-11.0.x`.
- [x] Assign issue to "build manager", who will stage the releases.
  + [ ] Create and use branches `release/<ver>` to perform version specific release work from.
  + [ ] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
  + [ ] Stage 9.4 release with Java 11.
  + [ ] Stage 10 release with Java 21.
  + [ ] Stage 11 release with Java 21.
  + [ ] Push release branches `release/<ver>` to to https://github.com/eclipse/jetty.project
  + [ ] Push release tags `jetty-<ver>` to https://github.com/eclipse/jetty.project
  + [ ] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
- [ ] Assign issue to "test manager", who will oversee the testing of the staged releases.
  + [ ] Test [CometD](https://github.com/cometd/cometd).
  + [ ] Test [Reactive HttpClient](https://github.com/jetty-project/jetty-reactive-httpclient).
  + [ ] Test [Load Generator](https://github.com/jetty-project/jetty-load-generator).
  + [ ] Test [Jetty Docker images](https://github.com/eclipse/jetty.docker).
  + [ ] Test other [Jetty OSS integrations](https://jenkins.webtide.net/job/external_oss).
  + [ ] Check [TCK CI](https://jenkins.webtide.net/job/tck).
  + [ ] Test sponsored integrations.
  + [ ] Check CI for performance regressions.
  + [ ] Notify interested parties and invite testing of the staged release(s).
  + [ ] Assign issue back to "release manager".
- [ ] Collect release votes from committers.
- [ ] Promote staged releases.
- [ ] Merge release branches back to main branches and delete release branches.
- [ ] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [ ] Update Jetty versions on the website ( follow instructions in [jetty-website](https://github.com/eclipse/jetty-website/blob/master/README.md) ).
  + [ ] Update (or check) [Download](https://eclipse.dev/jetty/download.php) page is updated.
  + [ ] Update (or check) documentation page(s) are updated.
- [ ] Publish GitHub Releases.
- [ ] Prepare release announcement for mailing lists.
- [ ] Publish any [security advisories](https://github.com/eclipse/jetty.project/security/advisories).
  + [ ] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
  + [ ] Edit any issues for CVEs in github with their CVE number
- [ ] Notify downstream maintainers.
  + [ ] Eclipse p2 maintainer.
  + [ ] Docker maintainer.
  + [ ] Jenkins maintainer.
  + [ ] Other maintainers.

**Comment by olamy** [comment]
done via https://github.com/eclipse/jetty.project/issues/10646 no need of 2 issues
