### ISSUE TITLE
Jetty Releases 9.4.42, 10.0.4, 11.0.4

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6374]
**Jetty Versions:**
This release process will produce releases: 9.4.42, 10.0.4, 11.0.4

**Target Date:**
Week starting Jun 7, 2021

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty versions in the issue.  If a major version (Jetty 9, 10 or 11) is not released, indicate why.
- [x] Update the target release date in the issue.
- [x] Link this issue to the target GitHub Projects.
- [x] Assign this issue to a "release manager".
- [x] Review draft security advisories. Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Review the GitHub Projects for the releases.  Any PRs that are moved to subsequent releases should be commented on so their authors are informed.
- [x] Freeze projects by editing the GitHub Project names to "Jetty X.Y.Z FROZEN"
   + [x] Freeze 9.4.x GitHub Project
   + [x] Freeze 10.0.x/11.0.x GitHub Project
- [x] Verify that all PRs assigned to the GitHub Projects are merged into their branches.
- [x] Verify that branch `jetty-10.0.x` is merged to branch `jetty-11.0.x`.
- [x] Wait 24 hours from last change to the issues/PRs included in a FROZEN GitHub Project.
- [x] Assign issue to "build manager", who will stage the releases.
   + [x] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
   + [x] Stage Jetty 9.4.x using Java 11.
   + [x] Stage Jetty 10.0.x, 11.0.x using Java 16.
   + [x] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
- [x] Assign issue to "test manager", who will oversee the testing of the staged releases.
   + [x] Test CometD (https://github.com/cometd/cometd).
   + [x] Test Reactive HttpClient (https://github.com/jetty-project/jetty-reactive-httpclient).
   + [x] Test Load Generator (https://github.com/jetty-project/jetty-load-generator).
   + [x] Test Jetty Docker images (https://github.com/eclipse/jetty.docker).
   + [x] Test other Jetty integrations (https://jenkins.webtide.net/job/external_oss).
   + [x] Update Jetty versions on the web sites.
   + [x] Check TCK CI (https://jenkins.webtide.net/job/tck).
   + [x] Check CI for performance regressions.
- [x] Collect release votes from committers.
- [x] Promote staged releases.
- [x] Merge release branches back to main branches and delete release branches.
- [x] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [x] Publish GitHub Releases.
- [x] Prepare release announcement for mailing lists.
- [x] Publish any security advisories.
   + [x] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
- [x] Notify downstream maintainers.
    + [x] Eclipse p2 maintainer.
    + [x] Docker maintainer.
    + [x] Jenkins maintainer.
    + [x] Other maintainers.

**Comment by joakime** [comment]
The release checklist should be unique per version of release.
They are not in lock step

**Comment by gregw** [comment]
@joakime the individual steps that are not in lock step are already broken out.    There is also the second task in the list that allows releases too be dropped from the train if we want to do a 9 only cycle for example

**Comment by sbordet** [comment]
@WalkerWatch please prepare/send the annoucement and then close this issue.
