### ISSUE TITLE
Jetty Releases 10.0.5/11.0.5

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6389]
**Jetty Versions:**
This release process will produce releases: 10.0.5, 11.0.5.
These refreshers of the Jetty 10/11 are necessary for #6385, which is a blocker for the Eclipse IDE release train.

**Target Date:**
11 June 2021 - 14 June 2021

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty versions in the issue.  If a major version (Jetty 9, 10 or 11) is not released, indicate why.
- [x] Update the target release date in the issue.
- [x] Link this issue to the target GitHub Projects.
- [x] Assign this issue to a "release manager".
- [x] Review draft security advisories. Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [ ] Review the GitHub Projects for the releases.  Any PRs that are moved to subsequent releases should be commented on so their authors are informed.
- [ ] Freeze projects by editing the GitHub Project names to "Jetty X.Y.Z FROZEN"
   + [ ] Freeze 10.0.x/11.0.x GitHub Project
- [ ] Verify that all PRs assigned to the GitHub Projects are merged into their branches.
- [ ] Verify that branch `jetty-10.0.x` is merged to branch `jetty-11.0.x`.
- [ ] Wait 24 hours from last change to the issues/PRs included in a FROZEN GitHub Project.
- [ ] Assign issue to "build manager", who will stage the releases.
   + [ ] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
   + [ ] Stage Jetty 10.0.x, 11.0.x using Java 16.
   + [ ] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
- [ ] Assign issue to "test manager", who will oversee the testing of the staged releases.
   + [ ] Test CometD (https://github.com/cometd/cometd).
   + [ ] Test Reactive HttpClient (https://github.com/jetty-project/jetty-reactive-httpclient).
   + [ ] Test Load Generator (https://github.com/jetty-project/jetty-load-generator).
   + [ ] Test Jetty Docker images (https://github.com/eclipse/jetty.docker).
   + [ ] Test other Jetty integrations (https://jenkins.webtide.net/job/external_oss).
   + [ ] Update Jetty versions on the web sites.
   + [ ] Check TCK CI (https://jenkins.webtide.net/job/tck).
   + [ ] Check CI for performance regressions.
- [ ] Collect release votes from committers.
- [ ] Promote staged releases.
- [ ] Merge release branches back to main branches and delete release branches.
- [ ] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [ ] Publish GitHub Releases.
- [ ] Prepare release announcement for mailing lists.
- [ ] Publish any security advisories.
   + [ ] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
- [ ] Notify downstream maintainers.
    + [ ] Eclipse p2 maintainer.
    + [ ] Docker maintainer.
    + [ ] Jenkins maintainer.
    + [ ] Other maintainers.

**Comment by sbordet** [comment]
Replaced by #6390.
