### ISSUE TITLE
Jetty Releases 10.0.5/11.0.5

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6390]
**Jetty Versions:**
This release process will produce releases: 10.0.5, 11.0.5.
These refreshers of the Jetty 10/11 are necessary for #6385, which is a blocker for the Eclipse IDE release train.

**Target Date:**
11 June 2021 - 14 June 2021

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty version(s) in the issue.  
- [x] Update the target release date in the issue.
- [x] Link this issue to the target [project(s)](https://github.com/eclipse/jetty.project/projects).
- [x] Assign this issue to a "release manager".
- [x] Review [draft security advisories](https://github.com/eclipse/jetty.project/security/advisories). Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Review their issues/PRs assigned to the target [project(s)](https://github.com/eclipse/jetty.project/projects).  Any PRs that are moved to subsequent releases should be commented on so their authors are informed.
- [x] Freeze the target [project(s)](https://github.com/eclipse/jetty.project/projects) by editing their names to "Jetty X.Y.Z FROZEN"
- [x] Wait 24 hours from last change to the issues/PRs included in a FROZEN GitHub Project.
- [x] Verify target [project(s)](https://github.com/eclipse/jetty.project/projects) are complete.
- [x] Verify that branch `jetty-10.0.x` is merged to branch `jetty-11.0.x`.
- [x] Assign issue to "build manager", who will stage the releases.
   + [x] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
   + [x] Stage Release(s).
     - Staged 10.0.5 at https://oss.sonatype.org/content/repositories/jetty-1673/
     - SBOM report for 10.0.5 - https://sbom.lift.sonatype.com/report/T1-0ff0976f7f21c391f20f-77bd2ffca9309-1623422602-1a00b23c9c72432ca1ab8f01a9428988
     - Staged 11.0.5 at https://oss.sonatype.org/content/repositories/jetty-1674/
     - SBOM report for 11.0.5 - https://sbom.lift.sonatype.com/report/T1-0ff0976f7f21c391f20f-77bd2ffca9309-1623424437-7330e632b94e494cb0793266c142edfe
   + [x] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
- [x] Assign issue to "test manager", who will oversee the testing of the staged releases.
   + [x] Add [testing tick list](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/.github/test-ticklist.md) to the target [project(s)](https://github.com/eclipse/jetty.project/projects).
   + [x] Testing tick lists complete in all target project(s).
   + [x] Assign issue back to "release manager".
- [x] Promote staged releases.
- [x] Merge release branches back to main branches and delete release branches.
  + [x] Merge PR for 10.0.5 - #6401
  + [x] Merge PR for 11.0.5 - #6402 
- [x] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [x] Update Jetty versions on the web sites.
- [x] Publish GitHub Releases.
- [x] Prepare release announcement for mailing lists.
- [x] ~Publish any [security advisories](https://github.com/eclipse/jetty.project/security/advisories).~
   + [x] ~Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.~
- [x] Notify downstream maintainers.
    + [x] Eclipse p2 maintainer.
    + [x] Docker maintainer.
    + [x] Jenkins maintainer.
    + [x] Other maintainers.

**Comment by WalkerWatch** [comment]
@sbordet Release notification has gone out for this. Do I need to do something to notify downstream?
