### ISSUE TITLE
Jetty Releases 9.4.43, 10.0.6, 11.0.6

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6450]
**Jetty Versions:**
This release process will produce releases: 9.4.43, 10.0.6, 11.0.6

**Target Date:**
2021-06-28

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty version(s) in the issue.  
- [x] Update the target release date in the issue.
- [x] Link this issue to the target [project(s)](https://github.com/eclipse/jetty.project/projects).
- [x] Assign this issue to a "release manager".
- [x] Review [draft security advisories](https://github.com/eclipse/jetty.project/security/advisories). Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Review the issues/PRs assigned to the target [project(s)](https://github.com/eclipse/jetty.project/projects).  Any PRs that are moved to subsequent releases should be commented on so their authors are informed.
- [x] Freeze the target [project(s)](https://github.com/eclipse/jetty.project/projects) by editing their names to "Jetty X.Y.Z FROZEN"
- [x] Wait 24 hours from last change to the issues/PRs included in a FROZEN GitHub Project.
- [x] Verify target [project(s)](https://github.com/eclipse/jetty.project/projects) are complete.
- [x] Verify that branch `jetty-10.0.x` is merged to branch `jetty-11.0.x`.
- [x] Assign issue to "build manager", who will stage the releases.
   + [x] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
   + [x] Stage 9.4 release with Java 11.
      - Staged 9.4.43.v20210629 at https://oss.sonatype.org/content/repositories/jetty-1684/
   + [x] Stage 10 release with Java 16.
      - Staged 10.0.6 at https://oss.sonatype.org/content/repositories/jetty-1682/
   + [x] Stage 11 release with Java 16.
      - Staged 11.0.6 at https://oss.sonatype.org/content/repositories/jetty-1683/
   + [x] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
- [x] Assign issue to "test manager", who will oversee the testing of the staged releases.
   + [x] Add [testing tick list](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/.github/test-ticklist.md) to the target [project(s)](https://github.com/eclipse/jetty.project/projects).
   + [x] Testing tick lists complete in all target project(s).
   + [x] Notify interested parties and invite testing of the staged release(s).
   + [x] Assign issue back to "release manager".
- [x] Collect release votes from committers.
- [x] Promote staged releases.
- [x] Merge release branches back to main branches and delete release branches.
- [x] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [x] Update Jetty versions on the web sites.
   + [x] Update (or check) [Download](https://www.eclipse.org/jetty/download.php) page is updated.
   + [x] Update (or check) documentation page(s) are updated.
- [x] Publish GitHub Releases.
- [x] Prepare release announcement for mailing lists.
- [x] Publish any [security advisories](https://github.com/eclipse/jetty.project/security/advisories).
   + [x] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
- [x] Notify downstream maintainers.
    + [x] Eclipse p2 maintainer.
    + [x] Docker maintainer.
    + [x] Jenkins maintainer.
    + [x] Other maintainers.

**Comment by lachlan-roberts** [comment]
@joakime can you build and stage the releases for testing.

**Comment by joakime** [comment]
@lachlan-roberts the releases for 9.4.43, 10.0.6, and 11.0.6 are staged.

**Comment by joakime** [comment]
@lachlan-roberts Testing as shown that we broke a few things.
I've dropped the staged releases, as we need to reroll now.

**Comment by joakime** [comment]
Accidentally closed.
