### ISSUE TITLE
Jetty Releases 9.4.x, 10.0.y, 11.0.y

### ISSUE THREAD

**Issue by firoj07** [eclipse/jetty.project#6775]
**Jetty Versions:**
This release process will produce releases:

**Target Date:**

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty version(s) in the issue.  
- [x] Update the target release date in the issue.
- [x] Link this issue to the target [project(s)](https://github.com/eclipse/jetty.project/projects).
- [x] Assign this issue to a "release manager".
- [x] Review [draft security advisories](https://github.com/eclipse/jetty.project/security/advisories). Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Review the issues/PRs assigned to the target [project(s)](https://github.com/eclipse/jetty.project/projects).  Any PRs that are moved to subsequent releases should be commented on so their authors are informed.
- [x] Freeze the target [project(s)](https://github.com/eclipse/jetty.project/projects) by editing their names to "Jetty X.Y.Z FROZEN"
- [x] Wait 24 hours from last change to the issues/PRs included in a FROZEN GitHub Project.
- [x] Verify target [project(s)](https://github.com/eclipse/jetty.project/projects) are complete.
- [x] Verify that branch `jetty-10.0.x` is merged to branch `jetty-11.0.x`.
- [x] Assign issue to "build manager", who will stage the releases.
  + [x] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
  + [ ] Stage 9.4 release with Java 11.
  + [x] Stage 10 release with Java 16.
  + [x] Stage 11 release with Java 16.
  + [x] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
- [x] Assign issue to "test manager", who will oversee the testing of the staged releases.
  + [ ] Test [CometD](https://github.com/cometd/cometd).
  + [x] Test [Reactive HttpClient](https://github.com/jetty-project/jetty-reactive-httpclient).
  + [ ] Test [Load Generator](https://github.com/jetty-project/jetty-load-generator).
  + [x] Test [Jetty Docker images](https://github.com/eclipse/jetty.docker).
  + [ ] Test other [Jetty OSS integrations](https://jenkins.webtide.net/job/external_oss).
  + [ ] Check [TCK CI](https://jenkins.webtide.net/job/tck).
  + [ ] Test sponsored integrations.
  + [ ] Check CI for performance regressions.
  + [ ] Notify interested parties and invite testing of the staged release(s).
  + [ ] Assign issue back to "release manager".
- [ ] Collect release votes from committers.
- [ ] Promote staged releases.
- [ ] Merge release branches back to main branches and delete release branches.
- [ ] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [ ] Update Jetty versions on the web sites.
  + [ ] Update (or check) [Download](https://www.eclipse.org/jetty/download.php) page is updated.
  + [ ] Update (or check) documentation page(s) are updated.
- [ ] Publish GitHub Releases.
- [ ] Prepare release announcement for mailing lists.
- [ ] Publish any [security advisories](https://github.com/eclipse/jetty.project/security/advisories).
  + [ ] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
- [ ] Notify downstream maintainers.
  + [ ] Eclipse p2 maintainer.
  + [ ] Docker maintainer.
  + [ ] Jenkins maintainer.
  + [ ] Other maintainers.

**Comment by lachlan-roberts** [comment]
This issue template is only for committers to manage the release process.
