### ISSUE TITLE
Jetty Release 9.4.44

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6875]
**Jetty Versions:**
This release process will produce releases:
9.4.44

**Target Date:**
2021-09-27

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty version(s) in the issue.  
- [x] Update the target release date in the issue.
- [x] Link this issue to the target [project(s)](https://github.com/eclipse/jetty.project/projects).
- [x] Assign this issue to a "release manager".
- [x] Review [draft security advisories](https://github.com/eclipse/jetty.project/security/advisories). Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Create the GitHub Project(s) for the next releases.
- [x] Review the issues/PRs assigned to the target [project(s)](https://github.com/eclipse/jetty.project/projects).  Any PRs that are moved to subsequent releases should be commented on so their authors are informed.
- [x] Freeze the target [project(s)](https://github.com/eclipse/jetty.project/projects) by editing their names to "Jetty X.Y.Z FROZEN"
- [x] Wait 24 hours from last change to the issues/PRs included in a FROZEN GitHub Project.
- [x] Verify target [project(s)](https://github.com/eclipse/jetty.project/projects) are complete.
- [x] Assign issue to "build manager", who will stage the releases.
  + [x] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
  + [x] Stage 9.4 release with Java 11.
     - 9.4.44.v20210927 staged at https://oss.sonatype.org/content/repositories/jetty-1707/
  + [x] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
- [x] Assign issue to "test manager", who will oversee the testing of the staged releases.
  + [x] Test [CometD](https://github.com/cometd/cometd).
  + [x] Test [Reactive HttpClient](https://github.com/jetty-project/jetty-reactive-httpclient).
  + [x] Test [Load Generator](https://github.com/jetty-project/jetty-load-generator).
  + [x] Test [Jetty Docker images](https://github.com/eclipse/jetty.docker).
  + [x] Test other [Jetty OSS integrations](https://jenkins.webtide.net/job/external_oss).
  + [x] Check [TCK CI](https://jenkins.webtide.net/job/tck).
  + [x] Test sponsored integrations.
  + [x] Check CI for performance regressions.
  + [x] Notify interested parties and invite testing of the staged release(s).
  + [x] Assign issue back to "release manager".
- [x] Collect release votes from committers.
- [x] Promote staged releases.
- [x] Merge release branches back to main branches and delete release branches.
    PR to merge back opened at https://github.com/eclipse/jetty.project/pull/6952
- [x] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [x] Update Jetty versions on the web sites.
  + [x] Update (or check) [Download](https://www.eclipse.org/jetty/download.php) page is updated.
  + [x] Update (or check) documentation page(s) are updated.
- [x] Publish GitHub Releases.
- [x] Prepare release announcement for mailing lists.
- [x] Publish any [security advisories](https://github.com/eclipse/jetty.project/security/advisories).
  + [x] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
- [x] Notify downstream maintainers.
  + [x] Eclipse p2 maintainer.
  + [x] Docker maintainer.
  + [x] Jenkins maintainer.
  + [x] Other maintainers.

**Comment by gregw** [comment]
@sbordet I've ticked through to the build stage and assigned @joakime to build 9.4
We do need to split out 10 & 11
