### ISSUE TITLE
Jetty-12 hackathon issues

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#7721]
Issue that have come out of the Jetty-12-hackathon:
 + [x] The great renaming. Many names are not exactly right. At some stage we need to review names and have a big renaming.  
 + [x] `demandContent(Runnable)`. Are we happy with this now?  Yes. Perhaps some renaming (see above) for `demandContent(...)` -> `demand(...)`. 
 + [x] `Content readContent()` returns a sliced buffer from the network buffer. I wonder if it will be useful to provide an API such as `Content readContent(ByteBuffer)`, where the `ByteBuffer` is provided by the application, see #7688.
 + [x] `Handler`/`Processor` design?  Mostly happy with design, but there is still a question of times when we need to access the outer most wrapper, can this be done?   Currently we avoid this a little bit by passing wrapped request to response wrapper.  One example is request logging can only see the inner request/response. @gregw 
 + [x] The `HttpChannel` object is exposed on the `Request` interface, but this exposes internal methods like `setStream()` and `onRequest()`.  Also the contract between the `Connection` and the `HttpChannel` is not clearly defined (other than by `HttpStream`).  The app primarily used the `HttpChannel` to access `HttpConfiguration`, so we can perhaps hide `HttpChannel` from the app by adding extra methods to `ConnectionMetaData` and/or `Context`. @sbordet 
 + [x] Request signing?  Can we now implement it since we have better access to raw request?  Perhaps this is a request customizer or lower? @joakime    (Greg is little concerned that we might lose rel/absolute URI info in http/1). - delayed to 12.0.0.beta1 - see #9209
 + [x] Do not carry `URI` as a `HttpURI`, carry it as a string instead.  @sbordet to investigate.  @gregw dubious. 
 + [x] #7728
+ [x] Gather writes.  Our `Content.Writer` API has `ByteBuffer...` but this is not yet fully implemented and there are no examples of apps using this.   So is it worth the extra work to pass arrays and iterate, when it is mostly 0 or 1 buffers passed?   Alternately, should we be passing a `Content` object and have a `Content` that can have multiple buffers... or does that just introduce iteration on the read side? @lorban  (@lachlan-roberts has a PR that added `ByteBuffer...` to some infrastructure). Benchmarks/research on the costs of `...` would be interesting?  Split API into overloaded methods might help?
+ [x] `BufferedWriterHandler` @lachlan-roberts 
+ [x] Lock review.  `HttpChannel` has a lock that is taken on most methods. `HttpStream` also has an atomic state for success/failure.  We need to look if we can reduce the number of locks/atomics and the frequency we grab them. @sbordet 
+ [x] How are difficult URI encodings like %2F handled and how are static resources served by core and servlets: #7713 @joakime 
+ [x] deprecate usage of `Resource` and use `Path` more often. @joakime 
+ [x] Rather than maintain EE8 and EE9 modules, is it possible to generate EE8 from EE9 source?  Can this be done on the fly?  @janbartel / @olamy 
+ [x] review JPMS support. @sbordet 
+ [x] Review. How can we do a JNDI datasource that is used by both EE9 & EE10 @janbartel ?
+ [x] Ultimately after everything else is working... cross context dispatch @lachlan-roberts    There are some significant "use-cases" for this, but would be happy with a loop back client! 
+ [x] IdleTimeout handling.  Currently there is a partial implementation that doesn't pass all tests.  We need to be able to ignore idletimeout exceptions when we are dispatched into a servlet @sbordet @gregw
