### ISSUE TITLE
Jetty Releases 9.4.50

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8817]
**Jetty Versions:**
This release process will produce releases: 9.4.50

**Target Date:**

Nov 4 2022

**Tasks:**
- [x] Create the release(s) issue.
- [x] Update the target Jetty version(s) in the issue.  
- [x] Update the target release date in the issue.
- [x] Link this issue to the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects).
- [x] Assign this issue to a "release manager".
- [x] Review [draft security advisories](https://github.com/eclipse/jetty.project/security/advisories). Ensure that issues are created and assigned to GitHub Projects to capture any advisories that will be announced.
- [x] Update [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects)
  + [x] Create new project for the next releases (not this release).
  + [x] Ensure new project is public (not private)
  + [x] Freeze the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects) by editing their names to "Jetty X.Y.Z FROZEN"
  + [x] Review the issues/PRs assigned to the target [GitHub Project(s)](https://github.com/eclipse/jetty.project/projects).  Any tasks that are not-yet-started are moved to next releases.
- [x] Review dependabot status. [Manually](https://github.com/eclipse/jetty.project/network/updates) run dependabot if needed and review resulting PRs for inclusion.
- [x] Wait 24 hours from last change to the issues/PRs included in FROZEN GitHub Project(s).
- [x] Verify target [project(s)](https://github.com/eclipse/jetty.project/projects) are complete.
- [x] Assign issue to "build manager", who will stage the releases.
  + [x] Create and use branches `release/<ver>` to perform version specific release work from.
  + [x] Ensure `VERSION.txt` additions for each release will be meaningful, descriptive, correct text.
  + [x] Stage 9.4 release with Java 11.
  + [x] Push release branches `release/<ver>` to to https://github.com/eclipse/jetty.project
  + [x] Push release tags `jetty-<ver>` to https://github.com/eclipse/jetty.project
  + [x] Edit a draft release (for each Jetty release) in GitHub (https://github.com/eclipse/jetty.project/releases). Content is generated with the "changelog tool".
        Be mindful of the order you create multiple release drafts.  The first one created will be the "oldest" when published. (eg: Draft is 9, then 10, then 11)
        The last created "draft" will show up as "latest" in the github UI.
        If you have to reroll, you'll have to delete the drafts and recreate them (especially so if 9 w/timestamp is in the mix of releases being worked on)
- [x] Assign issue to "test manager", who will oversee the testing of the staged releases.
  + [x] Test [CometD](https://github.com/cometd/cometd).
  + [x] Test [Reactive HttpClient](https://github.com/jetty-project/jetty-reactive-httpclient).
  + [x] Test [Load Generator](https://github.com/jetty-project/jetty-load-generator).
  + [x] Test [Jetty Docker images](https://github.com/eclipse/jetty.docker).
  + [x] Test other [Jetty OSS integrations](https://jenkins.webtide.net/job/external_oss).
  + [x] Check [TCK CI](https://jenkins.webtide.net/job/tck).
  + [x] Test sponsored integrations.
  + [x] Check CI for performance regressions.
  + [x] Notify interested parties and invite testing of the staged release(s).
  + [x] Assign issue back to "release manager".
- [x] Collect release votes from committers.
- [x] Promote staged releases.
- [x] Merge release branches back to main branches and delete release branches.
- [x] Verify release existence in Maven Central by triggering the Jenkins builds of CometD.
- [x] Update Jetty versions on the web sites.
  + [x] Update (or check) [Download](https://www.eclipse.org/jetty/download.php) page is updated.
  + [x] Update (or check) documentation page(s) are updated.
- [x] Publish GitHub Releases in the order of oldest (eg: 9) to newest (eg: 11) (to ensure that "latest" in github is truly the latest)
- [x] Prepare release announcement for mailing lists.
- [x] Publish any [security advisories](https://github.com/eclipse/jetty.project/security/advisories).
  + [x] Edit `VERSION.txt` to include any actual CVE number next to correspondent issue.
  + [x] Edit any issues for CVEs in github with their CVE number
- [x] Notify downstream maintainers.
  + [x] #8818
  + [x] Docker maintainer.
  + [x] Jenkins maintainer.
  + [x] Other maintainers.

**Comment by joakime** [comment]
Changes in branch `jetty-9.4.x` since `jetty-9.4.49.v20220914`

* https://github.com/eclipse/jetty.project/compare/jetty-9.4.49.v20220914...jetty-9.4.x

**Comment by joakime** [comment]
Release 9.4.50.v20221107 is now staged at
https://oss.sonatype.org/content/repositories/jetty-1802

**Comment by joakime** [comment]
Staged `9.4.50.v20221107` has been dropped.

**Comment by joakime** [comment]
Release `9.4.50.v20221201` is now staged at
https://oss.sonatype.org/content/repositories/jetty-1806/

**Comment by joakime** [comment]
Done.
